title: Kate Hodges
logo: assets/img/circle-headshot.png
description: >
  *Geospatial Data Scientist*
  <br><br>
  ğŸ“ UCL Geography (First Class hons)
  ğŸ’» R | Python | ArcGIS | QGIS
  ğŸ”— <a href="https://www.linkedin.com/in/kate-hodges-54314528b">[LinkedIn]</a> <a href="https://github.com/katehodges1">[GitHub]</a>
  ğŸ“ London, UK
  <br><br>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
classes: wide
