title: Kate Hodges
logo: assets/img/circle-headshot.png
description: >
  <b>Geospatial Data Scientist</b> <br>
  <i>Harnessing machine learning, geospatial analytics & storytelling to transform messy data into powerful insights</i>
  <br><br>
  ğŸ“ UCL Geography (First Class hons) <br>
  ğŸ’» R | Python | ArcGIS | QGIS <br>
  ğŸ”— Visit my <a href="https://www.linkedin.com/in/kate-hodges-54314528b">LinkedIn</a> & <a href="https://github.com/katehodges1">GitHub</a> profiles<br>
  ğŸ“ London, UK
  <br><br>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
classes: wide
